### ISSUE TITLE
Doesn't work on my mac

### ISSUE THREAD

**Issue by flavono123** [yuttie/hydrangea-vim#3]
I installed with vim-plug and edited my `~/.config/nvim/init.vim` followed:
```
...
call plug#begin('~/.local/share/nvim/plugged')
Plug 'yuttie/hydrangea-vim'
...
" colorscheme
colorscheme hydrangea
set termguicolors
...
```
> E185: Cannot find color scheme 'hydrangea'

But it doesn't work with an above error. How can I fix it? 
My env.  is:
+ iTerm2 : Build 3.1.5
+ NeoVim: v0.2.2

**Comment by yuttie** [comment]
Thank you for your report!

I bought Mac recently, and I have just found your issue occurring in my environment too.
I will investigate the issue.

**Comment by alexozer** [comment]
@flavono123 Do you have `call plug#end()` in your `init.vim`?

**Comment by flavono123** [comment]
@yuttie Thanks, and @alexozer Yes I did.

I just fixed refer another vim color plugin installation; 
make `~/.config/nvim/colors/` dir, and move the `hydrangea.vim` manually.

I think it's about vim-plug config, but I followed [Exmaple on vim-plug README](https://github.com/junegunn/vim-plug#example).
(Now I change the plug dir from `~/.local/share/nvim/plugged` to `~/.config/nvim/plugged`, still work for other plugs but not this)

**Comment by flavono123** [comment]
@yuttie btw, How you did set the special characters for file formats such as in this README; Vim, Linux penguin🐧?

**Comment by flavono123** [comment]
@yuttie @alexozer Found a [solution](https://github.com/junegunn/vim-plug/issues/708) and I did not write the `colorscheme` after the `call plug#end()` actually in my `init.vim` 😹.. 

Sorry for confusing you, and hope to work it on your system too! 😍

**Comment by yuttie** [comment]
@flavono123 You solved your problem, that's great! 👍 
And, I also solved my problem, which was caused by a cache file created by a plugin manager.  

Because I just copied `~/.config/nvim` directory from my Linux box to the new Mac environment, some path names in the cache file were not valid on Mac and they prevented plugins, including hydrangea-vim, from being loaded.

**Comment by yuttie** [comment]
@flavono123 You noticed that small 🐧 !
You need to have [VimDevIcons](https://github.com/ryanoasis/vim-devicons) and a patched font installed to get such icons in your vim editor. 😎

**Comment by flavono123** [comment]
@yuttie Learn from you, thanks!! 🙌 😘
